CREATE OR REPLACE PROCEDURE PRC_INSERT_CLIENTE(
        XID         Cliente.id%TYPE,
        XLOGIN      Cliente.login%TYPE,
        XSENHA      Cliente.senha%TYPE
) LANGUAGE PLPGSQL AS
$$
DECLARE
BEGIN
    /*FUTUROS TRATAMENTOS*/
    DELETE FROM CLIENTE WHERE LOGIN = XLOGIN AND SENHA = XSENHA AND ID = XID;
END;$$;