CREATE OR REPLACE PROCEDURE PRC_INSERT_CLIENTE(
        XCPF        Cliente.cpf%TYPE,
        XNOME       Cliente.nome%TYPE,
        XLOGIN      Cliente.login%TYPE,
        XSENHA      Cliente.senha%TYPE,
        XEMAIL      Cliente.email%TYPE,
        XNASC       Cliente.dataNasc%TYPE
) LANGUAGE PLPGSQL AS
$$
DECLARE
BEGIN
    /*FUTUROS TRATAMENTOS*/
    INSERT INTO CLIENTE(CPF,NOME,LOGIN,SENHA,EMAIL,DATANASC,DATA_CADASTRO) VALUES(XCPF,XNOME,XLOGIN,XSENHA,XEMAIL,XNASC,CURRENT_DATE);
END;$$;

