DROP DATABASE IF EXISTS Shopizer;
CREATE DATABASE Shopizer;
USE Shopizer;
DROP TABLE IF EXISTS Cliente;
CREATE TABLE Cliente(
    id INT AUTO_INCREMENT NOT NULL,
	login VARCHAR(20) NOT NULL,
	senha VARCHAR(20) NOT NULL,
	nome VARCHAR(45) NOT NULL,
	email VARCHAR(45) NOT NULL,
	dataNasc DATETIME NOT NULL,
	data_cadastro DATETIME NOT NULL,
	PRIMARY KEY(id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;


DROP TABLE IF EXISTS Produto;
CREATE TABLE Produto(
	id INT AUTO_INCREMENT NOT NULL,
	desc_ VARCHAR(45) NOT NULL,
	desc_det VARCHAR(90) NOT NULL,
	altura FLOAT NOT NULL,
	comprimento FLOAT NOT NULL,
	peso FLOAT NOT NULL,
	largura FLOAT NOT NULL,
	complemento TEXT,
	categoria VARCHAR(45),
	PRIMARY KEY(id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS Endereco;
CREATE TABLE Endereco(
	id INT AUTO_INCREMENT NOT NULL,
	logradouro VARCHAR(45) NOT NULL,
	bairro VARCHAR(45) NOT NULL,
	cidade VARCHAR(45)NOT NULL,
	estado VARCHAR(45) NOT NULL,
	complemento VARCHAR(45) NOT NULL,
	id_cliente INT NOT NULL,
	CONSTRAINT FOREIGN KEY (id_cliente) REFERENCES Cliente(id),
	PRIMARY KEY(id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS Imagem;
CREATE TABLE Imagem(
	id INT AUTO_INCREMENT NOT NULL,
	id_produto INT NOT NULL,
	path TEXT NOT NULL,
	desc_ VARCHAR(45) NOT NULL,
	CONSTRAINT FOREIGN KEY (id_produto) REFERENCES Produto (id),
	PRIMARY KEY (id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS Cartao_credito;
CREATE TABLE Cartao_credito(
	id INT AUTO_INCREMENT NOT NULL,
	data_cadastro DATETIME NOT NULL,
	titular VARCHAR(45) NOT NULL,
	cpf_titular VARCHAR(16) NOT NULL,
	num_cartao VARCHAR(20) NOT NULL,
	cod_seg INT(3) NOT NULL,
	validade VARCHAR(6) NOT NULL,
	id_cliente INT NOT NULL,
	CONSTRAINT FOREIGN KEY (id_cliente) REFERENCES Cliente(id),
	PRIMARY KEY(id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS Boleto;
CREATE TABLE Boleto(
	id INT AUTO_INCREMENT NOT NULL,
	data_cadastro DATETIME NOT NULL,
	titular VARCHAR(45) NOT NULL,
	cpf_titular VARCHAR(16) NOT NULL,
	vencimento DATETIME NOT NULL,
	cod_barras VARCHAR(45) NOT NULL,
	PRIMARY KEY (id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS Pagamento;
CREATE TABLE Pagamento(
	id INT AUTO_INCREMENT NOT NULL,
	id_cartao INT NOT NULL,
	id_boleto INT NOT NULL,
	tipo_pgto INT NOT NULL,
	n_parcelas INT NOT NULL,
	vlr_parcelas FLOAT NOT NULL,
	vencimento DATETIME,
	CONSTRAINT FOREIGN KEY(id_cartao) REFERENCES Cartao_credito(id),
	CONSTRAINT FOREIGN KEY(id_boleto) REFERENCES Boleto(id),
	PRIMARY KEY(id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS Venda;
CREATE TABLE Venda(
	id INT AUTO_INCREMENT NOT NULL,
	data_cadastro DATETIME NOT NULL,
	descontos FLOAT NOT NULL,
	vlr_total FLOAT NOT NULL,
	id_cliente INT NOT NULL,
	id_pagamento INT NOT NULL,
	CONSTRAINT FOREIGN KEY(id_pagamento) REFERENCES Pagamento(id),
	CONSTRAINT FOREIGN KEY(id_cliente) REFERENCES Cliente(id),
	PRIMARY KEY (id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;
DROP TABLE IF EXISTS Produto_Venda;
CREATE TABLE Produto_Venda(
	id INT AUTO_INCREMENT NOT NULL,
	id_produto INT NOT NULL,
	id_venda INT NOT NULL,
	qtd_produto FLOAT NOT NULL,
	vlr_unit FLOAT NOT NULL,
	vlr_total FLOAT NOT NULL,
	CONSTRAINT FOREIGN KEY(id_produto) REFERENCES Produto(id),
	CONSTRAINT FOREIGN KEY(id_venda) REFERENCES Venda(id),
	PRIMARY KEY(id))
	ENGINE = InnoDB
	DEFAULT CHARSET = utf8;
	